Second
EvgeniaKomleva/2018-FS-21-FRONTEND-KOMLEVA pull request #2
Opened 2018-10-14 11:39 UTC by EvgeniaKomleva

2018-10-15 21:00 UTC, martinkomitsky commented on dist/main.js
> +!function(n){var t={};function o(e){if(t[e])return t[e].exports;var r=t[e]={i:e,l:!1,exports:{}};return n[e].call(r.exports,r,r.exports,o),r.l=!0,r.exports}o.m=n,o.c=t,o.d=function(n,t,e){o.o(n,t)||O
Удалить

2018-10-17 19:47 UTC, martinkomitsky requested changes
Исправить:
1. В `webpack.config` у тебя нету ни entry, ни output. Как в `/dist` попадает твой main.js? Кто его собирает?
2. Непонятно, как запустить проект. Он должен запускаться и работать, чтобы я мог его проверить :(

2018-10-17 20:13 UTC, EvgeniaKomleva commented
я не понимаю что вы от меня хотите, у меня на компе все работает 


>Среда, 17 октября 2018, 22:48 +03:00 от Martin <notifications@github.com>:
>
>@martinkomitsky requested changes on this pull request.
>Исправить:
>*  В webpack.config у тебя нету ни entry, ни output. Как в /dist попадает твой main.js?
>*  Непонятно, как запустить проект. Он должен запускаться и работать, чтобы я мог его проверить :(
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

С уважением,
Евгения Комлева
komleva.1999@inbox.ru

2018-10-17 20:18 UTC, martinkomitsky commented
@EvgeniaKomleva попробуй склонировать проект в отдельную папку и попробовать там все запустить. Получится?

2018-10-17 20:29 UTC, EvgeniaKomleva commented
Ну я же по вашей просьбе убрала dist gitignore


>Среда, 17 октября 2018, 23:18 +03:00 от Martin <notifications@github.com>:
>
>@EvgeniaKomleva попробуй склонировать проект в отдельную папку и попробовать там все запустить. Получится?
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

С уважением,
Евгения Комлева
komleva.1999@inbox.ru

2018-10-18 11:50 UTC, martinkomitsky commented
> Ну я же по вашей просьбе убрала dist gitignore

Так и есть. Это как раз для того, чтобы каждый разработчик имел возможность собирать сам твой проект. У тебя сборка через webpack не работает. Работу не могу ни проверить, ни принять.

2018-10-18 14:33 UTC, martinkomitsky requested changes
![image](https://user-images.githubusercontent.com/14847018/47161938-b039c380-d2fb-11e8-9b80-8fba4de8d55b.png)
1. Исправь в package.json версии webpack и добавь webpack-cli, если хочешь, чтобы твой текущуй webpack.config.js работал и запускался.
2. Твоя сборка все равно будет выглядеть так, поэтому ее надо исправить:
![image](https://user-images.githubusercontent.com/14847018/47162026-e6774300-d2fb-11e8-9d52-b364b508f1b3.png)

2018-10-20 18:26 UTC, closed without merging